"""testing something

Revision ID: 1e6c1a0562ea
Revises: ffdc0a98111c
Create Date: 2022-07-21 16:08:08.165684

"""
from alembic import op
import sqlalchemy as sa
import os

environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = "1e6c1a0562ea"
down_revision = "ffdc0a98111c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("private", sa.Boolean(), nullable=True),
        sa.Column("picture", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    if environment == "production":
        op.execute(f"ALTER TABLE servers SET SCHEMA {SCHEMA};")

    op.create_table(
        "channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serverId", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["serverId"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    if environment == "production":
        op.execute(f"ALTER TABLE channels SET SCHEMA {SCHEMA};")

    op.create_table(
        "server_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=False),
        sa.Column("serverId", sa.Integer(), nullable=False),
        sa.Column("adminStatus", sa.Boolean(), nullable=True),
        sa.Column("muted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["serverId"],
            ["servers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id", "userId", "serverId"),
    )
    if environment == "production":
        op.execute(f"ALTER TABLE server_users SET SCHEMA {SCHEMA};")

    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userId", sa.Integer(), nullable=True),
        sa.Column("channelId", sa.Integer(), nullable=True),
        sa.Column("message", sa.String(length=1500), nullable=True),
        sa.ForeignKeyConstraint(
            ["channelId"],
            ["channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["userId"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    if environment == "production":
        op.execute(f"ALTER TABLE messages SET SCHEMA {SCHEMA};")

    op.add_column("users", sa.Column("photo", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "photo")
    op.drop_table("messages")
    op.drop_table("server_users")
    op.drop_table("channels")
    op.drop_table("servers")
    # ### end Alembic commands ###
